name: Mod Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Installer NuGet client
        uses: nuget/setup-nuget@v1

      - name: Setup tModLoader
        uses: chi-rei-den/ModLoaderTools@v1.1
        with:
          command: setup

      - name: Restore NuGet Packages
        run: nuget restore Localizer.sln

      - name: Build Mod
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Localizer.sln /p:Configuration=Release /p:Platform=x86

      - name: Patch Mod
        run: '& "$ENV:GITHUB_WORKSPACE\ModPatch\bin\Release\net472\ModPatch.exe"'

      - name: Publish Mod
        if: github.ref == 'refs/heads/master'
        uses: chi-rei-den/ModLoaderTools@v1
        with:
          command: publish
          path: Localizer
        env:
          steamid64: ${{ secrets.steamid64 }}
          passphrase: ${{ secrets.mod_browser_passphrase }}

      - name: Clean artifact
        run: |
          mkdir .\Artifact\Artifact\
          Copy-Item -Path "$ENV:UserProfile\Documents\My Games\Terraria\ModLoader\Mods\*" -Destination .\Artifact\Artifact
          del .\Artifact\Artifact\enabled.json

      - uses: actions/upload-artifact@master
        with:
          name: Build Artifact
          path: Artifact

      - name: Run Tests
        run: |
          copy .\LocalizerTest\bin\Release\net472\tModLoader.exe .\LocalizerTest\bin\Release\net472\Terraria.exe
          & "$ENV:UserProfile\.nuget\packages\xunit.runner.console\2.4.1\tools\net472\xunit.console.x86.exe" ".\LocalizerTest\bin\Release\net472\LocalizerTest.dll"
